# Generated by Django 4.2.5 on 2023-09-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_members_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_returned',
            field=models.CharField(default='no', max_length=200),
        ),
    ]
