# Generated by Django 4.2.5 on 2023-09-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_librarybook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarybook',
            old_name='book_id',
            new_name='bookID',
        ),
    ]
