# Generated by Django 4.2.5 on 2023-09-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='debt',
            field=models.IntegerField(default=0),
        ),
    ]
